### ISSUE TITLE
Cucumber scala plugin seems to be broken on 15.0v

### ISSUE THREAD

**Issue by tigran10** [danielwegener/intellij-cucumber-scala#12]
I am not able to run any feature files at all,  seems that plugin is not picking up any of them. Also the navigation between features and steps is not working as well. We have same problem on every machine with 15.0 intellij installed. The only way to run tests is through runner class which will run all of them. 

Cheers,
Tigran

**Comment by danielwegener** [comment]
Hi @tigran10,

thanks for the report. I'll have a look into this soon.

**Comment by danielwegener** [comment]
This will not work today anymore. The sbt tooling is broken since jetbrains decided not to release intellij15 through team city.

**Comment by danielwegener** [comment]
The release train is rolling, update should be within your IDE within 2 days.

**Comment by tigran10** [comment]
Thanks @danielwegener , much appreciated !

**Comment by tigran10** [comment]
Just updated the plugin, works like a charm, cheers @danielwegener
