### ISSUE TITLE
Support IntelliJ 2016.1

### ISSUE THREAD

**Issue by danielwegener** [danielwegener/intellij-cucumber-scala#18]
Do whatever needs to be done to support Support IntelliJ 2016.1 :)

**Comment by danielwegener** [comment]
fixed by #19

**Comment by danielwegener** [comment]
Cheers @athieriot ! 0.3.4 is [released](https://github.com/danielwegener/intellij-cucumber-scala/releases/tag/0.3.4) and should be in the [plugins repo](https://plugins.jetbrains.com/plugin/7460?pr=idea) soon.

**Comment by athieriot** [comment]
Hey that's fantastic :)

Thank you for being so fast !
