### ISSUE TITLE
Unable to find step definitions

### ISSUE THREAD

**Issue by binil** [danielwegener/intellij-cucumber-scala#20]
![screen shot 2016-05-31 at 12 44 02 am](https://cloud.githubusercontent.com/assets/58774/15667039/e76d9354-26c8-11e6-98f3-26e10e098b9d.png)

I am trying to run the `basic_arithmetic.feature`, but the runner can't seem to find the steps. I am trying the basic cucumber-scala code, and my project is set up with Gradle. Here are the file contents:

```
$ find . -type file -exec cat {} \; -print
apply plugin: 'scala'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.scala-lang:scala-library:2.11.7'    
    testCompile 'info.cukes:cucumber-scala_2.11:1.2.3'
    testCompile 'info.cukes:cucumber-junit:1.2.3'
    testCompile 'junit:junit:4.12'
}

./build.gradle
package cukes.rpncalc

import collection.mutable.Stack

sealed trait Arg

object Arg{
  implicit def op(s:String) = Op(s)
  implicit def value(v:Double) = Val(v)
}

case class Op(value: String) extends Arg
case class Val(value: Double) extends Arg

class RpnCalculator {
  private val stack = new Stack[Double]

  private def op(f: (Double, Double) => Double) =
    stack push f(stack.pop(), stack.pop())

  def push(arg: Arg) {
    arg match {
      case Op("+") => op(_ + _)
      case Op("-") => op(_ - _)
      case Op("*") => op(_ * _)
      case Op("/") => op(_ / _)
      case Val(value) => stack push value
    }
  }

  def value = stack.head
}
./src/main/scala/cukes/rpncalc/RpnCalculator.scala
@foo
Feature: Basic Arithmetic

  Scenario: Adding
  # Try to change one of the values below to provoke a failure
    When I add 4 and 5
    Then the result is 9

./src/test/resources/cukes/rpncalc/basic_arithmetic.feature
package cukes.rpncalc

import cucumber.api.Scenario
import cucumber.api.scala.{EN, ScalaDsl}
import org.junit.Assert._

class RpnCalculatorStepDefinitions extends ScalaDsl with EN {

  val calc = new RpnCalculator

  When("""^I add (\d+) and (\d+)$"""){ (arg1: Double, arg2: Double) =>
    calc push arg1
    calc push arg2
    calc push "+"
  }

  Then("^the result is (\\d+)$") { expected: Double =>
    assertEquals(expected, calc.value, 0.001)
  }

  Before("~@foo"){ scenario : Scenario =>
    println("Runs before scenarios *not* tagged with @foo")
  }
}
./src/test/scala/cukes/rpncalc/RpnCalculatorStepDefinitions.scala
package cukes.rpncalc

import cucumber.api.junit.Cucumber
import org.junit.runner.RunWith

@RunWith(classOf[Cucumber])
class RunCukesTest
./src/test/scala/cukes/rpncalc/RunCukesTest.scala
$
```

**Comment by danielwegener** [comment]
@binil Sorry to disappoint you, but this issue is rather related to cucumber-jvm/cucumber-jvm-scala or the cucumber-java intellij plugin.

This plugin here, intellij-cucumber-scala, does only provide the mechanism for glue code lookup in the editor. The actual test-execution is not influenced by it.

But yes, it is a bit confusing though ;)

**Comment by danielwegener** [comment]
Might be something with the gradle classpath that intellij tries to extract. But I am not so much into gradle+scala+intellij.

**Comment by binil** [comment]
Thanks @danielwegener !

I tried a java+gradle project and the step definitions were discovered correctly. Let me open a ticket with cucumber-java-plugin.

**Comment by binil** [comment]
@danielwegener FYI, I raised this bug with Cucumber Java plugin and was promptly Declined. See https://youtrack.jetbrains.com/issue/IDEA-156907.

**Comment by danielwegener** [comment]
@binil Maybe you did forgot to add the Glue parameter (the package that contains your glue code) to your the Test runner?
![screen shot 2016-06-02 at 10 16 06](https://cloud.githubusercontent.com/assets/2953619/15738389/51dce580-28ab-11e6-807c-63d7f8190f8a.png)

**Comment by binil** [comment]
@danielwegener Ah, that was it! I added `cukes.rpncalc` as the glue and things work now. Thanks!
