### ISSUE TITLE
Update Plugin to 2016.3EAP - (>163.0)

### ISSUE THREAD

**Issue by justgook** [danielwegener/intellij-cucumber-scala#23]
looks like u need to update `<depends>cucumber</depends>`  to `<depends>cucumber-java</depends>`

**Comment by danielwegener** [comment]
Thanks, good to know. I'll investigate it this weekend.

**Comment by justgook** [comment]
any updates ?

**Comment by danielwegener** [comment]
Sorry - busy weeks. Could you please give https://github.com/danielwegener/intellij-cucumber-scala/releases/tag/0.3.6 a quick try? If you are happy, I'll publish it at the jetbrains plugin repo.

**Comment by justgook** [comment]
![screen shot 2016-10-31 at 10 05 52](https://cloud.githubusercontent.com/assets/306976/19847774/c9332c4e-9f51-11e6-997a-dc78e5161c96.png)
looks like You forgot update dependencies (haven't look at code but i think it is about dependencies renaming as mention in first comment)

**Comment by danielwegener** [comment]
Thanks for testing. Sorry that it took a while to keep up. Just published 0.3.7 (now also to the jetbrains repo).

**Comment by justgook** [comment]
all works as expected ..
