### ISSUE TITLE
Plugin does not recognize step definitions in InteliJ Idea 2017.1

### ISSUE THREAD

**Issue by pjedruszuk** [danielwegener/intellij-cucumber-scala#26]
After updating Idea to 2017.1 and Cucumber for Scala plugin to 2017.1.1, my steps are not recognized anymore:
![stepsnotrecognized](https://cloud.githubusercontent.com/assets/2520338/24350190/9bf548bc-12e1-11e7-9203-d43e5525e7f7.PNG)

Java steps are recognized properly, it seems, that only Scala is not being picked up.

**Comment by danielwegener** [comment]
I think we released the 2017.1.1 too early (there seem to be a new incompatible scala plugin in the recent 2017.1EAP).

**Comment by danielwegener** [comment]
Could somone please verify that https://github.com/danielwegener/intellij-cucumber-scala/releases/tag/2017.1.2 (the jar from the download section) works? If it does, I'll push it to the jenkins plugin store asap.

**Comment by mfoody** [comment]
Your updated jar worked for me. Thanks so much for creating and maintaining this project.

**Comment by sinwe** [comment]
It works for me too

**Comment by alinaboghiu** [comment]
Yep, works, thank you!!

**Comment by danielwegener** [comment]
Aight, thanks for the retest. Ill publish it to the plugin repo.

**Comment by danielwegener** [comment]
https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/33898

**Comment by danielwegener** [comment]
Ah yeah, all credits to @pbyrne84 - he/she took the time to dig into the idea-scala plugin code! Thanks for your contribution!

**Comment by sinwe** [comment]
As I commented [here](https://github.com/danielwegener/intellij-cucumber-scala/issues/15), this issue happens again in 2017.2 EAP
