### ISSUE TITLE
Add support for latest intellij 2017.3

### ISSUE THREAD

**Issue by zatekusen** [danielwegener/intellij-cucumber-scala#29]
Could you please update the plugin to support intellij 2017.3

**Comment by pbyrne-mdsol** [comment]
[Update_versions_2017.3.patch.zip](https://github.com/danielwegener/intellij-cucumber-scala/files/1528620/Update_versions_2017.3.patch.zip)

The scala version updated. This is a patch with the dependencies

**Comment by jaina00** [comment]
Hi .. m getting

Fail to load plugin descriptor from file Update_versions_2017.3.patch.zip

I downloaded the zip file and did "Install plugin from disk".

Regards

**Comment by siliconcat** [comment]
That is just the patch to apply to the code. After applying the patch and packaging the application, you get the following plugin which you can install from disk...

[intellij-cucumber-scala_2.12-2017.3.zip](https://github.com/danielwegener/intellij-cucumber-scala/files/1531889/intellij-cucumber-scala_2.12-2017.3.zip)

**Comment by danielwegener** [comment]
Please try https://github.com/danielwegener/intellij-cucumber-scala/releases/tag/2017.3.0 and close the issue when everything works for you.

**Comment by zatekusen** [comment]
Thanks very much, the latest version is working well.
