### ISSUE TITLE
Broken again on Intellij 2018.2

### ISSUE THREAD

**Issue by lawrencecraft** [danielwegener/intellij-cucumber-scala#39]
Hi,

Just FYI, this appears to be broken once again on the latest update of Intellij. I get the same behavior that was observed earlier: no Cucumber steps match.

**Comment by pbyrne-mdsol** [comment]
I will look into it. I have a question for @danielwegener, do you really want to keep the until version? It might be better to remove it and actually let it break when it is truly broken. Intellij is not very good at warning it will be broken anyway.

This also may be the last time I look at this plugin for a while. Not to sure about how cucumber filled my future will be.

**Comment by danielwegener** [comment]
please try again:
https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/49133

**Comment by danielwegener** [comment]
thanks for your patience and contributions @pbyrne-mdsol :)

**Comment by pbyrne-mdsol** [comment]
My pleasure  @danielwegener - though after tomorrow this account is technically dead. 

I will switch back to my @pbyrne84.

I think I may of found a replacement for me if I do not end up doing cucumber again for a while.

**Comment by danielwegener** [comment]
Please try https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/77214
