### ISSUE TITLE
cucumber plugin is not available for IDEA 2018.2.1

### ISSUE THREAD

**Issue by Seetaramayya** [danielwegener/intellij-cucumber-scala#42]
I am not able to install cucumber plugin for `Intellij community version 2018.2.1` either through `plugin` window or manual [download link](https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala).

This might be related to [issue 39](https://github.com/danielwegener/intellij-cucumber-scala/issues/39).

**Comment by danielwegener** [comment]
please try again
https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/49133
