### ISSUE TITLE
Not compatible with latest IntelliJ/Scala plugin (2018.2 and 2018.2.10)

### ISSUE THREAD

**Issue by kditrj2d** [danielwegener/intellij-cucumber-scala#43]
The issue described in https://github.com/danielwegener/intellij-cucumber-scala/issues/34 has re-appeared with the release of IntelliJ 2018.2 and JetBrains Scala plugin 2018.2.10.

See the comment at the end of issue #34

**Comment by pbyrne-mdsol** [comment]
I think this never released
https://github.com/danielwegener/intellij-cucumber-scala/pull/41

Version number should be 2018.2.0
https://github.com/danielwegener/intellij-cucumber-scala/pull/41/files

Which is not what this page lists
https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala

**Comment by kditrj2d** [comment]
This is a duplicate of https://github.com/danielwegener/intellij-cucumber-scala/pull/41
Closing...
