### ISSUE TITLE
Support for Intellij 14.1

### ISSUE THREAD

**Issue by aaronmgomez** [danielwegener/intellij-cucumber-scala#9]
plugin is no longer compatible with Intellij v14.1

**Comment by otros-systems** [comment]
+1

**Comment by danielwegener** [comment]
I gonna look into it this evening. Maybe it's just upgrading the manifest, it will depend if the intellij-scala plugin made a binary incompatible scala upgrade.

**Comment by danielwegener** [comment]
0.3.1 hit the road: https://plugins.jetbrains.com/plugin/7460?pr=idea
Feel free to close this issue if it works for you - due to lack of time and patience to setup the Idea SDK on this laptop, this is rather a blind, untested release.

**Comment by aaronmgomez** [comment]
Great, working again now, thanks
